language: ruby
rvm:
  - 2.0.0

services:
  - redis-server
  - memcached
  - postgresql

env:
  - SECRET_TOKEN=travis 

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database photographerio_test;' -U postgres

notifications:
  webhooks:
    - http://afternoon-hubot.herokuapp.com/hubot/travis
